# Generated by Django 4.1.1 on 2022-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='goal_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_goal',
            field=models.IntegerField(null=True),
        ),
    ]
