# Generated by Django 4.1.1 on 2022-09-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_dailyrecord_goal_status_habit_target_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='uom',
            new_name='unit_of_measure',
        ),
    ]
